config:
  use_colors: true

jaffle_shop:
  target: "{{ env_var('ENVIRONMENT', 'dev') }}"
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USER', 'dev') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dev') }}"
      port: 5432
      dbname: postgres
      schema: "{{ env_var('POSTGRES_SCHEMA', 'dev') }}"
      threads: 4
